version: '3.9'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd app && alembic upgrade head && cd .. && uvicorn app.main:app --reload --host 0.0.0.0"
    ports:
      - "8000:8000"
    env_file:
      - /app/.env
    depends_on: 
      database:
        condition: service_healthy
  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - /app/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d fastapi_docker_db -U common_user"] # todo: any better way? Specifying user and db manually does not look good
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - database
    

volumes:
  postgres_data:
  