version: '3.9'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - /app/.env
    depends_on: 
      - database
  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - /app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - database
    

volumes:
  postgres_data:
  