version: '3.9'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - /app/.env
    depends_on: 
      - database
  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - /app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

volumes:
  postgres_data:
  