version: '3.9'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on: 
      - database
    networks:
      - mynetwork
  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=common_user
      - POSTGRES_PASSWORD=default_password
      - POSTGRES_DB=fastapi_docker_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U common_user"]
      interval: 5s
      timeout: 10s
      retries: 5
    expose:
      - "5432"
    networks:
      - mynetwork
    
networks:
 mynetwork:
  